### ISSUE TITLE
Update list on home page after create new todo

### ISSUE THREAD

**Issue by bangbu10820** [bangbu10820/flutter-todo#13]
We need to reflect change when create a new todo.

#12 has already create a TodoListModel and provide it to HomePage and descendants widget, TodoListModel already contains a list and a method to add new Todo to the list.

To add new todo, we can simple call `context.read<TodoListModel>().add(new Todo())`. Since MyHomePage use `todos` list from `TodoListModel`, and `add` method already call `notifyListener`, the change will be reflected

**Comment by AnyaQuote** [comment]
Closed by #16
